# Manipulación de Arrays

**Pregunta 1:** Dado un array numpy unidimensional de tamaño 10, redimensiona este array a una matriz de tamaño 5x2.

array --> [45,23,6,7,4,9,25,14,47,66]

resultado:

[45  9]

[23 25]

[ 6 14]

[ 7 47]

[ 4 66]

In [1]:
import numpy as np

array = np.array([45, 23, 6, 7, 49, 25, 14, 47, 66, 9])
resultado = array.reshape(5, 2, order='F')

print(resultado)

[[45 25]
 [23 14]
 [ 6 47]
 [ 7 66]
 [49  9]]


**Pregunta 2:** Dado un array numpy bidimensional de tamaño 3x4, redimensiona este array a un vector unidimensional.

array -->
 
[45,23,6,33]

[10,3,44,28]

[28,72,52,22]

Resultado -->  [45 10 28 23  3 72  6 44 52 33 28 22]
 

In [3]:
import numpy as np

array = np.array([
    [45, 23,  6, 33],
    [10,  3, 44, 28],
    [28, 72, 52, 22]
])

resultado = array.ravel(order='F')   
print(resultado)

[45 10 28 23  3 72  6 44 52 33 28 22]


**Pregunta 3:** Generar un array unidimensional con 24 elementos aleatorios a continuación:

* Redimiensionar a un array bidimensional de tamaño 4x6 
* Redimensionar a partir del anterior a un array tridimensional de tamaño 2x3x4.

In [4]:
import numpy as np

# Array unidimensional con 24 elementos aleatorios
array_1d = np.random.randint(1, 100, 24)

# Redimensionar a 4x6
array_2d = array_1d.reshape(4, 6)

# Redimensionar a 2x3x4
array_3d = array_2d.reshape(2, 3, 4)

print("Array 1D:")
print(array_1d)

print("\nArray 2D (4x6):")
print(array_2d)

print("\nArray 3D (2x3x4):")
print(array_3d)

Array 1D:
[39 49 13 78 40 41 42 93 93  6 65 66 80 28 53 59 82 89 74 16 92 75 35 73]

Array 2D (4x6):
[[39 49 13 78 40 41]
 [42 93 93  6 65 66]
 [80 28 53 59 82 89]
 [74 16 92 75 35 73]]

Array 3D (2x3x4):
[[[39 49 13 78]
  [40 41 42 93]
  [93  6 65 66]]

 [[80 28 53 59]
  [82 89 74 16]
  [92 75 35 73]]]


**Pregunta 4:** Dado un array numpy bidimensional A de tamaño 3x3 y un array numpy bidimensional B de tamaño 3x2, crea un nuevo array que sea la concatenación horizontal de A y B.

In [5]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [10, 11],
    [12, 13],
    [14, 15]
])

resultado = np.hstack((A, B))
print(resultado)

[[ 1  2  3 10 11]
 [ 4  5  6 12 13]
 [ 7  8  9 14 15]]


**Pregunta 5:** Dado un array numpy bidimensional A de tamaño 4x4, divide este array en dos arrays, uno que contenga las dos primeras filas y otro que contenga las dos últimas filas.

In [6]:
import numpy as np

A = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13,14, 15, 16]
])

array_1 = A[:2, :]
array_2 = A[2:, :]

print("Dos primeras filas:")
print(array_1)

print("\nDos últimas filas:")
print(array_2)

Dos primeras filas:
[[1 2 3 4]
 [5 6 7 8]]

Dos últimas filas:
[[ 9 10 11 12]
 [13 14 15 16]]


**Pregunta 6:** Dado un array numpy unidimensional de tamaño 10, inserta un nuevo elemento en la posición 5 y elimina el elemento en la posición 3.

In [7]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,10])

# Insertar un nuevo elemento en la posición 5
array = np.insert(array, 5, 99)

# Eliminar el elemento en la posición 3
array = np.delete(array, 3)

print(array)

[ 1  2  3  5 99  6  7  8  9 10]


Una forma sensilla de filtrar valores dentro de un array es pasando un array de valores booleanos, veamos:


In [1]:
import numpy as np 

a = np.array([5,2,4,7,8])
filtrado = a[[True,False,True,False,True]]
print(filtrado)

[5 4 8]


**Pregunta 7:** Basandose en el ejemplo anterior y los conocimientos sobre operadores de relación generar un array  unidimensional de tamaño 15 y elementos aleatorios, elimina todos los elementos que sean mayores que 10 y luego inserta el valor 20 al final del array resultante.

In [8]:

import numpy as np

# Array 1D de tamaño 15 con valores aleatorios
a = np.random.randint(1, 21, 15)  
print("Original:", a)

# Eliminar (quedarse SOLO con los <= 10)
a_filtrado = a[a <= 10]
print("Filtrado (<=10):", a_filtrado)

# Insertar 20 al final
resultado = np.append(a_filtrado, 20)
print("Resultado final:", resultado)

Original: [ 5 17 18 20 12  2 11  3 10  6 17  6 15 14  6]
Filtrado (<=10): [ 5  2  3 10  6  6  6]
Resultado final: [ 5  2  3 10  6  6  6 20]


**Pregunta 8:** Dado un array numpy bidimensional de tamaño 3x3, calcula la matriz transpuesta y la matriz inversa.

In [9]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

transpuesta = A.T
inversa = np.linalg.inv(A)

print("Matriz A:")
print(A)

print("\nTranspuesta:")
print(transpuesta)

print("\nInversa:")
print(inversa)

Matriz A:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Transpuesta:
[[1 0 5]
 [2 1 6]
 [3 4 0]]

Inversa:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


**Pregunta 9:** Dadas dos matrices numpy A y B de tamaño 3x3, calcula el producto matricial de A y B.

In [11]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

producto = A @ B   

print("Matriz A:")
print(A)

print("\nMatriz B:")
print(B)

print("\nProducto matricial A · B:")
print(producto)

Matriz A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Producto matricial A · B:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


**Pregunta 10:** Dado un array numpy bidimensional de tamaño 3x3, calcula la suma de los elementos en cada fila y la media de los elementos en cada columna.

In [12]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

suma_filas = np.sum(A, axis=1)
media_columnas = np.mean(A, axis=0)

print("Matriz A:")
print(A)

print("\nSuma de cada fila:")
print(suma_filas)

print("\nMedia de cada columna:")
print(media_columnas)

Matriz A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Suma de cada fila:
[ 6 15 24]

Media de cada columna:
[4. 5. 6.]


**Pregunta 11:** Dado un array numpy unidimensional de tamaño 10, calcula el producto acumulativo de los elementos del array y luego encuentra el índice del elemento máximo en el array resultante.

In [13]:
import numpy as np

# Array unidimensional de tamaño 10
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Producto acumulativo
producto_acumulativo = np.cumprod(a)

# Índice del elemento máximo
indice_maximo = np.argmax(producto_acumulativo)

print("Array original:")
print(a)

print("\nProducto acumulativo:")
print(producto_acumulativo)

print("\nÍndice del valor máximo:")
print(indice_maximo)

Array original:
[ 1  2  3  4  5  6  7  8  9 10]

Producto acumulativo:
[      1       2       6      24     120     720    5040   40320  362880
 3628800]

Índice del valor máximo:
9


**Pregunta 12:** Dado un array numpy unidimensional que representa las calificaciones de los estudiantes en un examen, calcula la media, la mediana y la desviación estándar de las calificaciones.

In [14]:
import numpy as np

calificaciones = np.array([5, 6, 7, 8, 9, 4, 6, 7, 8, 10])

media = np.mean(calificaciones)
mediana = np.median(calificaciones)
desviacion = np.std(calificaciones)

print("Calificaciones:")
print(calificaciones)

print("\nMedia:", media)
print("Mediana:", mediana)
print("Desviación estándar:", desviacion)

Calificaciones:
[ 5  6  7  8  9  4  6  7  8 10]

Media: 7.0
Mediana: 7.0
Desviación estándar: 1.7320508075688772


**Pregunta 13:** Dado un array numpy bidimensional que representa las edades de los estudiantes en una clase (filas representan diferentes grupos de edad y columnas representan diferentes géneros), calcula la moda de las edades en cada grupo de edad y género.

In [15]:
import numpy as np

edades = np.array([
    [20, 21, 20],
    [22, 22, 23]
])

def moda(array):
    valores, conteos = np.unique(array, return_counts=True)
    return valores[np.argmax(conteos)]

# Moda por fila (grupo de edad)
moda_por_grupo = np.apply_along_axis(moda, axis=1, arr=edades)

# Moda por columna (género)
moda_por_genero = np.apply_along_axis(moda, axis=0, arr=edades)

print("Edades:")
print(edades)

print("\nModa por grupo de edad (filas):")
print(moda_por_grupo)

print("\nModa por género (columnas):")
print(moda_por_genero)

Edades:
[[20 21 20]
 [22 22 23]]

Moda por grupo de edad (filas):
[20 22]

Moda por género (columnas):
[20 21 20]



**Pregunta 13:** Un investigador está estudiando el rendimiento académico de un grupo de estudiantes en dos asignaturas: Matemáticas y Ciencias. Ha recopilado las calificaciones finales de los estudiantes en ambas asignaturas y quiere obtener algunas estadísticas descriptivas.

El array de calificaciones está estructurado de la siguiente manera:

* La primera columna representa las calificaciones de los estudiantes en Matemáticas.
* La segunda columna representa las calificaciones de los estudiantes en Ciencias.


Por cada asignatura calcule media, mediana y desviación estandar. Y saque sus conclusiones respecto al rendimiento.


[85, 90]

[70, 75]

[90, 85]

[65, 80]

[75, 70]

In [2]:
import numpy as np

# Calificaciones: columna 0 = Matemáticas, columna 1 = Ciencias
calificaciones = np.array([
    [85, 90],
    [70, 75],
    [90, 85],
    [65, 80],
    [75, 70]
])

# Matemáticas
media_mat = np.mean(calificaciones[:, 0])
mediana_mat = np.median(calificaciones[:, 0])
desv_mat = np.std(calificaciones[:, 0])

# Ciencias
media_cien = np.mean(calificaciones[:, 1])
mediana_cien = np.median(calificaciones[:, 1])
desv_cien = np.std(calificaciones[:, 1])

print("Matemáticas:")
print("Media:", media_mat)
print("Mediana:", mediana_mat)
print("Desviación estándar:", desv_mat)

print("\nCiencias:")
print("Media:", media_cien)
print("Mediana:", mediana_cien)
print("Desviación estándar:", desv_cien)

Matemáticas:
Media: 77.0
Mediana: 75.0
Desviación estándar: 9.273618495495704

Ciencias:
Media: 80.0
Mediana: 80.0
Desviación estándar: 7.0710678118654755


El rendimiento es mayor y más regular en Ciencias, mientras que en Matemáticas las calificaciones son más variables.

#### Utilizando máscaras

**Pregunta 15:**  Dado un array numpy unidimensional de tamaño 10 que representa las ventas diarias de una tienda, encuentra todos los días en los que las ventas superaron los 100 dólares.

array ----> [85, 110, 90, 130, 95, 105, 120, 140, 75, 115]

In [3]:
import numpy as np

ventas = np.array([85, 110, 90, 130, 95, 105, 120, 140, 75, 115])

dias = np.where(ventas > 100)[0]      # índices (días) donde supera 100
valores = ventas[ventas > 100]        # ventas que superan 100

print("Días (índices) con ventas > 100:", dias)
print("Ventas > 100:", valores)

Días (índices) con ventas > 100: [1 3 5 6 7 9]
Ventas > 100: [110 130 105 120 140 115]


**Pregunta 16:** Dada una matriz numpy bidimensional que representa los resultados de un examen (filas representan estudiantes y columnas representan preguntas), encuentra todos los estudiantes que respondieron correctamente a todas las preguntas.

Array

[1, 0, 1, 1]

[1, 1, 1, 0]

[1, 1, 1, 1]

[0, 0, 1, 1]

[1, 0, 0, 1]

In [4]:
import numpy as np

resultados = np.array([
    [1, 0, 1, 1],
    [1, 1, 1, 0],
    [1, 1, 1, 1],
    [0, 0, 1, 1],
    [1, 0, 0, 1]
])

# Máscara: estudiantes que tienen todos 1
mascara = np.all(resultados == 1, axis=1)

# Índices de los estudiantes
estudiantes = np.where(mascara)[0]

print("Estudiantes que respondieron todo correctamente:", estudiantes)

Estudiantes que respondieron todo correctamente: [2]


Aunque sólo un estudiante respondió todo correctamente, se devuelve su índice para identificarlo, no el número total de estudiantes