# Fundamentos de NUMPY

**Pregunta 1:** Definir una array en de 4x6 con elementos enteros multiplos de 4, a continuación imprimir:

* Numero de dimensiones
* Forma
* Tamaño total

In [1]:
import numpy as np

# Crear array 4x6 con múltiplos de 4
array_4x6 = np.arange(4, 4*4*6 + 1, 4).reshape(4, 6)

# Imprimir resultados
print("Array:")
print(array_4x6)

print("Número de dimensiones:", array_4x6.ndim)
print("Forma:", array_4x6.shape)
print("Tamaño total:", array_4x6.size)

Array:
[[ 4  8 12 16 20 24]
 [28 32 36 40 44 48]
 [52 56 60 64 68 72]
 [76 80 84 88 92 96]]
Número de dimensiones: 2
Forma: (4, 6)
Tamaño total: 24


**Pregunta 2:** Definir un array con 25 elementos que se encuentren entre el 22 y el 38, a continuación imprimir los valores en los indices pares.

In [2]:
import numpy as np

# Crear array con 25 elementos entre 22 y 38
array = np.linspace(22, 38, 25)

# Imprimir valores en índices pares
print(array[::2])

[22.         23.33333333 24.66666667 26.         27.33333333 28.66666667
 30.         31.33333333 32.66666667 34.         35.33333333 36.66666667
 38.        ]


**Pregunta 3:** Dado el siguiente array en 3 dimensiones:
* Averiguar que forma tiene
* Acceder mendiante indices a los elementos remarcados en negrita. 

[[[  9  73  96  27  76]
  [ 90  **53**  44  72  72]
  [ 19  76  36  **37**   3]
  [ 78  89  84  21  69]]

 [[ 58   5  80  95  93]
  [ 39 **100**  24  81  28]
  [ 71  63  16  72  39]
  [ **83**  81  38  78 100]]

 [[ 84  **77**  35  35  26]
  [ 38   7  69  94  **29**]
  [ 40  85  82   9  48]
  [ 43  42 100 100  37]]]

In [3]:
import numpy as np

arr = np.array([
    [
        [9, 73, 96, 27, 76],
        [90, 53, 44, 72, 72],
        [19, 76, 36, 37, 3],
        [78, 89, 84, 21, 69]
    ],
    [
        [58, 5, 80, 95, 93],
        [39, 100, 24, 81, 28],
        [71, 63, 16, 72, 39],
        [83, 81, 38, 78, 100]
    ],
    [
        [84, 77, 35, 35, 26],
        [38, 7, 69, 94, 29],
        [40, 85, 82, 9, 48],
        [43, 42, 100, 100, 37]
    ]
])

# Forma del array
print(arr.shape)

# Elementos remarcados en negrita
print(arr[0,1,1])  # 53
print(arr[0,2,3])  # 37
print(arr[1,1,1])  # 100
print(arr[1,3,0])  # 83
print(arr[2,0,1])  # 77
print(arr[2,1,4])  # 29

(3, 4, 5)
53
37
100
83
77
29


**Pregunta 4:** Generar la siguiente matriz triangular, para ello solo debe ocupar un método de creación.

[1., 1., 1., 1., 0.]

[1., 1., 1., 1., 1.]

[1., 1., 1., 1., 1.]

In [5]:
import numpy as np

m = np.triu(np.ones((3, 5), dtype=int))

print(m)

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]]


**Pregunta 5:** El último valor del array declarado no se imprime correctamente, evalue y solucione. A contuación explique a que se debe.   

In [22]:
import numpy as np 

a = np.array([24,10,366],dtype=np.int8)
print(a)

[ 24  10 110]


C:\Users\gider\AppData\Local\Temp\ipykernel_25396\2640448207.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 366 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([24,10,366],dtype=np.int8)


In [6]:
import numpy as np

a = np.array([24, 10, 366], dtype=np.int16)
print(a)

[ 24  10 366]


El último valor no se imprime correctamente porque el array se crea con el tipo np.int8,cuyo rango es de -128 a 127. El valor 366 excede ese rango y provoca overflow. Se soluciona utilizando un tipo de dato mayor como np.int16.

**Pregunta 6:** Mediante slicing obtener los elementos marcados en negrita del siguiente array.

[ 58   5  80  95  93]

[ 39 **100**  **24**  81  28]

[ 71  **63**  **16**  72  39]

[ 83  **81**  **38**  78 100]

In [7]:
import numpy as np

arr = np.array([
    [58,  5, 80, 95, 93],
    [39, 100, 24, 81, 28],
    [71, 63, 16, 72, 39],
    [83, 81, 38, 78, 100]
])

arr[1:4, 1:3]

array([[100,  24],
       [ 63,  16],
       [ 81,  38]])

**Pregunta 7:** Utilizando nditer iterar sobre las filas el siguiente array. 

[ 58   5  80  95  93]

[ 39 100 24  81  28]

[ 71  63  16  72  39]

[ 83  81  38  78 100]

In [11]:
import numpy as np

arr = np.array([
    [58,  5, 80, 95, 93],
    [39, 100, 24, 81, 28],
    [71, 63, 16, 72, 39],
    [83, 81, 38, 78, 100]
])

for fila in np.nditer(arr, flags=['external_loop','buffered'], 
                      buffersize=arr.shape[1], order='C'):
    print(fila)


[58  5 80 95 93]
[ 39 100  24  81  28]
[71 63 16 72 39]
[ 83  81  38  78 100]


**Pregunta 8:** Dada la siguiente matriz, convertirla en una matriz triangular inferior.

[58 92 88 84]

[ 5 23 90 31]

[97 32  7 94]

[87 84 10 23]

In [12]:
import numpy as np

arr = np.array([
    [58, 92, 88, 84],
    [5,  23, 90, 31],
    [97, 32, 7,  94],
    [87, 84, 10, 23]
])

np.tril(arr)

array([[58,  0,  0,  0],
       [ 5, 23,  0,  0],
       [97, 32,  7,  0],
       [87, 84, 10, 23]])

**Pregunta 9:** Crear un array de tipo datetime con elementos entre 2010/10 y 2011/11.

In [13]:
import numpy as np

fechas = np.arange(
    np.datetime64('2010-10'),
    np.datetime64('2011-12'),
    dtype='datetime64[M]'
)

fechas

array(['2010-10', '2010-11', '2010-12', '2011-01', '2011-02', '2011-03',
       '2011-04', '2011-05', '2011-06', '2011-07', '2011-08', '2011-09',
       '2011-10', '2011-11'], dtype='datetime64[M]')

**Pregunta 10:** Utilizando el array de la pregunta anterior se desea obtener la diferencia de cada una de las fechas con respecto al 07/10/2015. Obtener cada una de las diferencias y guardarlas en un array.

In [14]:
import numpy as np

fechas = np.arange(
    np.datetime64('2010-10'),
    np.datetime64('2011-12'),
    dtype='datetime64[M]'
)

referencia = np.datetime64('2015-10-07')

diferencias = referencia - fechas
diferencias

array([1832, 1801, 1771, 1740, 1709, 1681, 1650, 1620, 1589, 1559, 1528,
       1497, 1467, 1436], dtype='timedelta64[D]')